name: aws-express-app

services:
  psql-db:
    build:
      context: psql-db
    hostname: ${POSTGRES_URL}
    container_name: express-app-db
    restart: on-failure:3
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-certs:/var/lib/postgresql/certs
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  proxy:
    build:
      context: proxy
    container_name: express-app-proxy
    hostname: proxy.express-app.com
    volumes:
      - "/var/log/nginx:/var/log/nginx"
    environment:
      - EXPRESS_PORT=${EXPRESS_PORT}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - express-app

  express-app:
    build:
      context: express-app
    hostname: app.express-app.com
    container_name: express-app
    restart: on-failure:3
    env_file: .env
    ports:
      - "${EXPRESS_PORT}:${EXPRESS_PORT}"
    depends_on:
      - psql-db

volumes:
  db-data:
  db-certs: