branch-defaults:
  main:
    environment: null
    group_suffix: null
global:
  application_name: aws-express-app
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: admin
  repository: https://github.com/Israelvdr/aws-express-app.git
  sc: git
  workspace_type: Application
