INSERT INTO questions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
('What does the "A" in AWS stand for?', 'Amazon', 'Apple', 'Azure', 'Alibaba', 'A'),
('Which AWS service is used for object storage?', 'RDS', 'S3', 'EC2', 'Lambda', 'B'),
('Which AWS service is used for running virtual servers?', 'Lambda', 'EC2', 'S3', 'CloudFront', 'B'),
('What is AWS Lambda primarily used for?', 'Hosting websites', 'Managing databases', 'Running code without servers', 'Storing files', 'C'),
('Which AWS service provides a NoSQL database?', 'RDS', 'DynamoDB', 'Aurora', 'Redshift', 'B'),
('Which AWS service is used for content delivery?', 'CloudFront', 'Route 53', 'Elastic Beanstalk', 'IAM', 'A'),
('Which AWS service helps manage user access and permissions?', 'IAM', 'EC2', 'CloudWatch', 'S3', 'A'),
('What does EC2 stand for?', 'Elastic Compute Cloud', 'Enterprise Cloud Console', 'External Cloud Connector', 'Elastic Container Cluster', 'A'),
('Which AWS service is used for monitoring and logging?', 'CloudTrail', 'CloudWatch', 'IAM', 'SNS', 'B'),
('Which AWS service is used for sending notifications?', 'SES', 'SNS', 'SQS', 'CloudWatch', 'B'),
('Which AWS service is used for relational databases?', 'DynamoDB', 'RDS', 'S3', 'Lambda', 'B'),
('What is the AWS global DNS service?', 'CloudFront', 'Route 53', 'Elastic Load Balancing', 'IAM', 'B'),
('Which AWS service allows container orchestration?', 'Lambda', 'ECS', 'S3', 'CloudTrail', 'B'),
('Which AWS service is used to automate infrastructure deployment?', 'CloudFormation', 'CloudWatch', 'IAM', 'S3', 'A'),
('Which AWS service is used for machine learning?', 'SageMaker', 'Lambda', 'EC2', 'CloudTrail', 'A'),
('Which AWS service provides scalable file storage?', 'EFS', 'S3', 'RDS', 'DynamoDB', 'A'),
('Which AWS service is used for archiving data?', 'S3', 'Glacier', 'EBS', 'CloudFront', 'B'),
('Which AWS service is used for managing secrets and credentials?', 'IAM', 'Secrets Manager', 'CloudTrail', 'S3', 'B'),
('Which AWS service helps migrate databases to AWS?', 'DMS', 'RDS', 'EC2', 'CloudFront', 'A'),
('Which AWS service is used for serverless APIs?', 'API Gateway', 'EC2', 'CloudFront', 'S3', 'A');